# Generated by Django 5.2.15 on 2026-06-27 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=30)),
                ('action', models.CharField(max_length=300)),
                ('target', models.CharField(blank=True, default='', max_length=500)),
                ('log_type', models.CharField(choices=[('auth', 'Autentifikatsiya'), ('content', 'Kontent'), ('payment', "To'lov"), ('enroll', 'Yozilish'), ('security', 'Xavfsizlik'), ('settings', 'Sozlamalar'), ('test', 'Test')], default='content', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(default='ProSkill IT Academy', max_length=200)),
                ('contact_email', models.EmailField(default='info@proskill.uz', max_length=254)),
                ('telegram', models.CharField(default='@proskill_bot', max_length=100)),
                ('registration_open', models.BooleanField(default=True)),
                ('auto_unlock', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('telegram_notifications', models.BooleanField(default=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Platforma sozlamalari',
                'verbose_name_plural': 'Platforma sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=5)),
                ('text', models.TextField()),
                ('reply', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('visible', "Ko'rinadi"), ('hidden', 'Yashirin')], default='visible', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_ref', models.CharField(blank=True, default='', max_length=100)),
                ('text', models.TextField()),
                ('answer', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('unanswered', 'Javobsiz'), ('answered', 'Javoblangan')], default='unanswered', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_questions', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_questions', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(choices=[('valid', 'Amal qiladi'), ('revoked', 'Bekor qilingan')], default='valid', max_length=20)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_at'],
                'unique_together': {('student', 'course')},
            },
        ),
    ]
